### ISSUE TITLE
Semantic HTML & form elements

### ISSUE THREAD

**Issue by jsms90** [fac-13/phac-kpnet#61]
Hey all :smile: 

A couple of little things about [the form](https://github.com/fac-13/phac-kpnet/blob/master/index.html#L26-L31):
```
<label>
    <form>
        <input type="text" id="search-box">
        <input type="submit" id="submit-button" value="Search">
    </form>
</label>
```

1. Even though inputs can be styled to look like buttons, it's better to use the HTML5 `button` element. 

This should also fix the fact that I can't currently use my keyboard to tab between the search box and the search button.

2. There's a `label` element that's not being used & is currently wrapped around your `form`. [Here's a little refresher on what the label element is](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label)

When you're creating forms, you want to be associating a `label` element with each `input` field & putting some text in that label.

[This article](https://www.coolfields.co.uk/2011/04/accessible-forms-should-every-input-have-a-label/) explains why it matters for accessibility & how to implement this in your code.

Note: for your use case, you probably want to look at the "Hiding Labels" section, which has a link refering to 'Text for Screen Readers Only'

**Comment by iPhatty** [comment]
Fixed changes along #63
